apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-infra
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sarubhai/test-argocd-app-dependency.git
    targetRevision: HEAD
    # path: infra-apps
    path: app-of-apps-infra
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      # - RespectIgnoreDifferences=true
