apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sarubhai/test-argocd-app-dependency.git
    targetRevision: HEAD
    path: infra-charts/reloader
    # helm:
    #   releaseName: reloader
    #   valueFiles:
    #     - values.yaml
    #   version: v3
  destination:
    name: in-cluster
    namespace: reloader
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
