apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/sarubhai/test-argocd-app-dependency.git
    targetRevision: HEAD
    path: infra-charts/reloader
    helm:
      releaseName: reloader
      valueFiles:
        - values.yaml
      version: v3
  destination:
    name: reloader
    namespace: reloader
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
