apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sarubhai/test-argocd-app-dependency.git
    targetRevision: HEAD
    path: infra-charts/trust-manager
    # helm:
    #   releaseName: trust-manager
    #   valueFiles:
    #     - values.yaml
    #   version: v3
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # - ApplyOutOfSyncOnly=true
      # - ServerSideApply=true
      # - RespectIgnoreDifferences=true
