reloader:
  reloader:
    watchGlobally: true
    # ignoreNamespaces: "default"
    enableHA: false
    deployment:
      replicas: 1
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          # cpu: 100m
          memory: 512Mi
    rbac:
      enabled: true
    serviceAccount:
      create: true
    serviceMonitor:
      enabled: false
    verticalPodAutoscaler:
      enabled: false
