apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-frontend
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "3"  
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sarubhai/test-argocd-app-dependency.git
    targetRevision: HEAD
    path: ./manifests/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: my-frontend
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
