{{- range .Values.clusters }}
{{- if .infra.enabled }}
{{- if .infra.trustManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{printf "%s-%s" .name "trust-manager"}}
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/sarubhai/test-argocd-app-dependency.git
    targetRevision: {{ .infra.trustManager.version }}
    path: infra-charts/trust-manager
    helm:
      releaseName: trust-manager
      valueFiles:
        - {{ .infra.valueFiles }}
      version: v3
  destination:
    name: {{ .name }}
    namespace: cert-manager
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      # - RespectIgnoreDifferences=true
{{- end }}
{{- end }}
---
{{- end }}
